/*
* DON'T TOUCH!
* This file is generated by python script AUTOMATICALLY!
*
* Generated base on: {0}
* Type name: {1}
* Tester:    int {1}_tester();
*
* Json keep-word: 
    "__default_value_fields__": [], # Take value in .json file as the default value of cpp variable
    "__optional_fields__": [], # Not require to present to .json file, but always in cpp struct
    "__assign_type_fields__": {{"field":"cpp-type"}}, # Assign specal cpp-type of field, but not infer automatically as default.
    "__assign_enum_fields__": {{"field":"enum-type"}}, # Assign specal enum-type of field, but not infer automatically as default.
                              enum-type need have implemented _toSting() & _fromString() functions.
    "__assign_set_lists__": [], # Take list in .json file as std::set<>, but not std::vector<> as default
    "__comment__xxx":"", # Add comment line
    "__sqlite_capable__":"", # enable sqlite tableIO autogen
    "__sqlite_primary__":"", # assign the primary key of sqlite, if not assigned, first existing col of [ 'id', 'date', 'mktCode', 'datetime', 'code'] will be assigned automatically.
* Script author: ChinSaiki<chinsaiki@outlook.com>
*/
#pragma once


#include "types/s4type.h"
#include "db_sqlite/tableIO.h"
#include <SQLiteCpp/ExecuteMany.h>

#include "jsonTypes/s4_history_trade_t.h"

namespace S4 {
namespace sqlite {

class s4_history_trade_t_dbTbl : public tableIO_t<struct s4_history_trade_t>{
public:
    typedef struct s4_history_trade_t data_t;
	//s4_history_trade_t_dbTbl(const std::string name)
    //{
    //    set_name(name);
    //};
    
	virtual void set_name(const std::string& name) override {
        m_name = name;
        m_qurey_build = "CREATE TABLE if not exists " + m_name + K_COL;
        m_qurey_insert = "INSERT OR IGNORE INTO " + m_name + K_IN;
    }

    virtual const std::string & get_query_build(void) const override { return m_qurey_build;};

    virtual const std::string & get_query_insert(void) const override { return m_qurey_insert;};
    
    virtual void bind_query(SQLite::Statement& query, const std::vector<struct s4_history_trade_t>& data, size_t nb) override
    {
        const struct s4_history_trade_t & K_data = data[nb];
        query.bind(1, K_data.id);
		query.bind(2, K_data.date);
		query.bind(3, K_data.stgName);
		query.bind(4, K_data.mktCodeStr);
		query.bind(5, K_data.time_utcSec);
		query.bind(6, K_data.datetime);
		query.bind(7, trade_opt_t_toString(K_data.optType));
		query.bind(8, K_data.position);
		query.bind(9, K_data.status);
		query.bind(10, K_data.order_open);
		query.bind(11, K_data.order_take);
		query.bind(12, K_data.order_stop);
		query.bind(13, K_data.order_close);
		query.bind(14, K_data.order_vol);
		query.bind(15, K_data.deal_open);
		query.bind(16, K_data.deal_close);
		query.bind(17, K_data.deal_vol);
		query.bind(18, K_data.deal_amt);
		query.bind(19, K_data.commission);
		query.bind(20, K_data.stamp_duty);
		query.bind(21, K_data.transfer_fee);
		query.bind(22, K_data.other_fees);
		query.bind(23, K_data.remarks);
    }

    //warning: not clear data inside, but append DB.data to it
    virtual void load_query(SQLite::Statement& query, std::vector<s4_history_trade_t>& data) override
    {
        struct s4_history_trade_t K_data;
        K_data.id = (int64_t)query.getColumn(0).getInt64();
		K_data.date = (time_date_t)query.getColumn(1).getInt64();
		K_data.stgName = (std::string)query.getColumn(2).getString();
		K_data.mktCodeStr = (std::string)query.getColumn(3).getString();
		K_data.time_utcSec = (time_utcSec_t)query.getColumn(4).getInt64();
		K_data.datetime = (std::string)query.getColumn(5).getString();
		K_data.optType = trade_opt_t_fromString(query.getColumn(6).getString());
		K_data.position = (std::string)query.getColumn(7).getString();
		K_data.status = (std::string)query.getColumn(8).getString();
		K_data.order_open = (price_t)query.getColumn(9).getInt64();
		K_data.order_take = (price_t)query.getColumn(10).getInt64();
		K_data.order_stop = (price_t)query.getColumn(11).getInt64();
		K_data.order_close = (price_t)query.getColumn(12).getInt64();
		K_data.order_vol = (vol_share_t)query.getColumn(13).getInt64();
		K_data.deal_open = (price_t)query.getColumn(14).getInt64();
		K_data.deal_close = (price_t)query.getColumn(15).getInt64();
		K_data.deal_vol = (vol_share_t)query.getColumn(16).getInt64();
		K_data.deal_amt = (amount_t)query.getColumn(17).getDouble();
		K_data.commission = (amount_t)query.getColumn(18).getDouble();
		K_data.stamp_duty = (amount_t)query.getColumn(19).getDouble();
		K_data.transfer_fee = (amount_t)query.getColumn(20).getDouble();
		K_data.other_fees = (amount_t)query.getColumn(21).getDouble();
		K_data.remarks = (std::string)query.getColumn(22).getString();
        data.push_back(std::move(K_data));
    }

private:
	//std::string m_name;
    std::string m_qurey_build;
    std::string m_qurey_insert;
private:

const std::string K_COL =
    "( "
        "id	INTEGER, "
        "date	INTEGER, "
        "stgName	TEXT, "
        "mktCodeStr	TEXT, "
        "time_utcSec	INTEGER, "
        "datetime	TEXT, "
        "optType	TEXT, "
        "position	TEXT, "
        "status	TEXT, "
        "order_open	INTEGER, "
        "order_take	INTEGER, "
        "order_stop	INTEGER, "
        "order_close	INTEGER, "
        "order_vol	INTEGER, "
        "deal_open	INTEGER, "
        "deal_close	INTEGER, "
        "deal_vol	INTEGER, "
        "deal_amt	DOUBLE, "
        "commission	DOUBLE, "
        "stamp_duty	DOUBLE, "
        "transfer_fee	DOUBLE, "
        "other_fees	DOUBLE, "
        "remarks	TEXT, "

        "PRIMARY KEY(id, time_utcSec, status)"
    ")";



const std::string K_IN =
    "("
    "id, date, stgName, mktCodeStr, time_utcSec, datetime, optType, position, status, order_open, order_take, order_stop, order_close, order_vol, deal_open, deal_close, deal_vol, deal_amt, commission, stamp_duty, transfer_fee, other_fees, remarks"
    ") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
;


};

}//namespace sqlite
}//namespace S4
